CREATE DATABASE IF NOT EXISTS feedback_form;

USE feedback_form;

CREATE TABLE contacts (
 id BIGINT(60) NOT NULL,
 name VARCHAR(100) NOT NULL,
 email VARCHAR(100) NOT NULL,
 message VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE contacts ADD PRIMARY KEY (`id`);

ALTER TABLE contacts MODIFY `id` bigint(60) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;
